//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handyman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class handymanEntities : DbContext
    {
        public handymanEntities()
            : base("name=handymanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_seq> customer_seq { get; set; }
        public virtual DbSet<handyman> handymen { get; set; }
        public virtual DbSet<handyman_ability> handyman_ability { get; set; }
        public virtual DbSet<handyman_seq> handyman_seq { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<request_detail> request_detail { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
