//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handyman
{
    using System;
    using System.Collections.Generic;
    
    public partial class handyman_ability
    {
        public int handyman_ability_id { get; set; }
        public string handyman_id { get; set; }
        public int ability_skill_id { get; set; }
        public string skill_license_no { get; set; }
        public Nullable<System.DateTime> license_issued_date { get; set; }
    
        public virtual handyman handyman { get; set; }
        public virtual skill skill { get; set; }
    }
}
