//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handyman
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_detail
    {
        public int request_detail_id { get; set; }
        public int request_id { get; set; }
        public int service_id { get; set; }
        public string handyman_id { get; set; }
        public Nullable<int> request_staus_id { get; set; }
        public Nullable<System.DateTime> expected_work_date { get; set; }
        public Nullable<System.DateTime> fixed_date { get; set; }
    
        public virtual handyman handyman { get; set; }
        public virtual request request { get; set; }
        public virtual service service { get; set; }
        public virtual status status { get; set; }
    }
}
